#!/bin/bash
set -e

# Create auto-merge PR for progress updates

echo "=== Creating Auto-Update PR ==="

# Check for changes
if git diff --quiet && git diff --staged --quiet; then
    echo "No changes to commit"
    exit 0
fi

# Get current date in JST
DATE=$(TZ='Asia/Tokyo' date '+%Y-%m-%d')
BRANCH_NAME="auto-update/${DATE}"

# Check if branch already exists
if git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
    echo "Branch $BRANCH_NAME already exists, updating..."
    git checkout "$BRANCH_NAME"
    git pull origin "$BRANCH_NAME" || true
else
    echo "Creating new branch: $BRANCH_NAME"
    git checkout -b "$BRANCH_NAME"
fi

# Add and commit changes
git add -A
git commit -m "Update ISE report progress: ${DATE}" || {
    echo "Nothing to commit"
    exit 0
}

# Push branch
git push origin "$BRANCH_NAME" --force

# Check if PR already exists
EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number' 2>/dev/null || echo "")

if [ -n "$EXISTING_PR" ]; then
    echo "PR #$EXISTING_PR already exists"
else
    # Create PR
    PR_URL=$(gh pr create \
        --title "Update ISE report progress: ${DATE}" \
        --body "Automated progress update for ISE reports.

This PR was automatically generated by GitHub Actions.

## Changes
- Updated progress data
- Generated new README with current statistics
- Created daily snapshot" \
        --base main \
        --head "$BRANCH_NAME")

    echo "Created PR: $PR_URL"

    # Extract PR number
    PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')

    # Enable auto-merge
    if [ -n "$PR_NUMBER" ]; then
        gh pr merge "$PR_NUMBER" --auto --squash || echo "Auto-merge not available"
    fi
fi

echo "=== Auto-Update PR Complete ==="
