#!/bin/bash
set -e

# Create auto-update PR with progress changes

# Check if WORKFLOW_PAT secret is configured
if [ -z "$GH_TOKEN" ]; then
    echo "Error: WORKFLOW_PAT secret is not configured"
    exit 1
fi

# Check if there are any changes
git add -A

if git diff --cached --quiet; then
    echo "No changes to commit"
    exit 0
fi

# Create unique branch name with timestamp
DATE=$(TZ='Asia/Tokyo' date +%Y-%m-%d)
TIMESTAMP=$(TZ='Asia/Tokyo' date +%Y%m%d-%H%M%S)
BRANCH_NAME="auto-update-${TIMESTAMP}"

# Create and switch to new branch
git checkout -b "$BRANCH_NAME"

# Commit changes
git commit -m "Update ISE report progress: ${DATE}" \
    -m "" \
    -m "Automated daily update of ISE report progress dashboard."

# Push to remote
if ! git push origin "$BRANCH_NAME"; then
    echo "Error: Failed to push branch to remote"
    exit 1
fi

# Create pull request
PR_BODY="Automated progress update for ISE reports.

## Changes
- Updated progress data
- Generated new README with current statistics
- Created daily snapshot

This PR was automatically generated by GitHub Actions."

if ! PR_URL=$(gh pr create \
    --title "Update ISE report progress: ${DATE}" \
    --body "$PR_BODY" \
    --base main \
    --head "$BRANCH_NAME"); then
    echo "Error: Failed to create pull request"
    exit 1
fi

echo "Created PR: $PR_URL"

# Enable auto-merge
if ! gh pr merge "$PR_URL" --auto --squash; then
    echo "Warning: Failed to enable auto-merge"
    echo "PR created but auto-merge not enabled: $PR_URL"
    exit 1
fi

echo "Auto-merge enabled for PR: $PR_URL"
